"""add google_id to users

Revision ID: 4cc59002d1bc
Revises: 5263539d78df
Create Date: 2026-02-17 17:32:20.752250

"""
from typing import Sequence, Union
from sqlalchemy import inspect
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cc59002d1bc'
down_revision: Union[str, None] = '5263539d78df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col["name"] for col in inspector.get_columns("users")]

    if "google_id" not in columns:
        op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
        op.create_unique_constraint('users_google_id_key', 'users', ['google_id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
