"""add ondelete cascade to wishlist product

Revision ID: 66e02f4f7834
Revises: 
Create Date: 2026-02-13 19:26:53.610786

"""
from typing import Sequence, Union
from sqlalchemy import inspect
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e02f4f7834'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    bind = op.get_bind()
    inspector = inspect(bind)

    fks = [fk["name"] for fk in inspector.get_foreign_keys("orders")]
    if "orders_user_id_fkey" in fks:
        op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')

    op.create_foreign_key(
        'orders_user_id_fkey',
        'orders',
        'users',
        ['user_id'],
        ['user_id'],
        ondelete='CASCADE'
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlists', type_='foreignkey')
    op.create_foreign_key(op.f('wishlists_user_id_fkey'), 'wishlists', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
