"""add_product_tags_many_to_many

Revision ID: bc5ea4d74eb2
Revises: b61384200804
Create Date: 2026-02-23 17:32:10.207503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5ea4d74eb2'
down_revision: Union[str, None] = 'b61384200804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
